# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build on Dev Branch

on:
  push:
    branches:
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install Dependencies for Gioui
        run: sudo apt install -y gcc pkg-config libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev libvulkan-dev

      - name: Install Gioui
        run: go install gioui.org/cmd/gogio@latest

      - name: Make Directories if Not Exists
        run: mkdir -p ./build

      - name: Build
        run: make build

      - name: Check if build was successful
        run: |
          if [ ! -f ./build/diy-photoframe ]; then
            echo "Build failed, diy-photoframe not found!"
            exit 1
          fi
