name: Build and Release

on:
  push:
    branches:
      - "main" # Triggers on pushes to the main branch
    tags:
      - "v*.*.*" # Triggers on version tags

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install Dependencies for Gioui
        run: sudo apt install -y gcc pkg-config libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev libvulkan-dev

      - name: Install Gioui
        run: go install gioui.org/cmd/gogio@latest

      - name: Make Directories if Not Exists
        run: mkdir -p ./build

      - name: Build
        run: make build

      - name: Create a Git Tag (if not exists)
        run: |
          tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          git tag -f $tag
          git push origin $tag

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/diy-photoframe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
